export const SHEET = {
  radius: 30,
  fill: 'var(--surface)',
  open: { damping: 0.9, response: 0.38 },
  close: { damping: 1, response: 0.3 },
  projection: 0.16,
  settlePx: 0.1,
  dismissRatio: 0.3,
  listRadius: 22,
  listFill: 'rgba(var(--ink), 0.045)',
  tileHeight: 84,
  tileRadius: 24,
  tileFill: 'var(--surface-1)',
  tileArmed: '#8e1f1f',
  primaryHeight: 52,
  primaryFill: '#00417F',
  armTimeout: 3000,
} as const
