/** Types for the module generated by tools/vite-file-icons.ts. */
declare module 'virtual:file-icons' {
  /** URL of the Material Icon Theme icon for a file name. */
  export function fileIconUrl(name: string): string
  /** URL of the icon for a folder name, open or closed. */
  export function folderIconUrl(name: string, open: boolean): string
}
