// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function GetDetectedAgents():Promise<Array<auth.DetectedAgent>>;

export function GetLinkedProviders():Promise<Array<auth.ProviderID>>;

export function InitiateOAuth(arg1:string):Promise<auth.Credential>;

export function LinkDetectedAgent(arg1:string,arg2:string):Promise<auth.Credential>;
