// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {session} from '../models';

export function CoordinatorHistory():Promise<Array<domain.RuntimeEvent>>;

export function CoordinatorInterrupt():Promise<void>;

export function CoordinatorReset():Promise<void>;

export function CoordinatorSend(arg1:session.Config,arg2:string):Promise<string>;

export function GetProviderSettings(arg1:string):Promise<domain.ProviderSettings>;

export function InterruptTurn(arg1:string):Promise<void>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function ListProviders(arg1:boolean):Promise<Array<domain.ProviderSnapshot>>;

export function ListSessions():Promise<Array<domain.Session>>;

export function ListWorkspaces():Promise<Array<domain.Workspace>>;

export function ParseTasks(arg1:string):Promise<Array<session.TaskRequest>>;

export function RespondToApproval(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendTurn(arg1:domain.SendTurnInput):Promise<void>;

export function SpawnTasks(arg1:Array<session.SpawnRequest>,arg2:session.SpawnOptions):Promise<session.SpawnResult>;

export function StartSession(arg1:string,arg2:domain.SessionStartInput):Promise<domain.Session>;

export function StopSession(arg1:string):Promise<void>;

export function TaskHandoff(arg1:string):Promise<domain.TaskHandoff>;

export function ThreadHistory(arg1:string):Promise<Array<domain.RuntimeEvent>>;

export function UpdateProviderSettings(arg1:string,arg2:domain.ProviderSettings):Promise<void>;

export function WorkspaceTasks(arg1:string):Promise<Array<domain.Task>>;
