// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveProject() {
  return window['go']['main']['App']['ActiveProject']();
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function ChooseAttachments() {
  return window['go']['main']['App']['ChooseAttachments']();
}

export function ChooseProject() {
  return window['go']['main']['App']['ChooseProject']();
}

export function CompactWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CompactWorkspace'](arg1, arg2);
}

export function ContextStatus(arg1) {
  return window['go']['main']['App']['ContextStatus'](arg1);
}

export function CoordinatorHistory() {
  return window['go']['main']['App']['CoordinatorHistory']();
}

export function CoordinatorInterrupt() {
  return window['go']['main']['App']['CoordinatorInterrupt']();
}

export function CoordinatorReset() {
  return window['go']['main']['App']['CoordinatorReset']();
}

export function CoordinatorSend(arg1, arg2) {
  return window['go']['main']['App']['CoordinatorSend'](arg1, arg2);
}

export function CoordinatorSendFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['CoordinatorSendFiles'](arg1, arg2, arg3);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteTaskHistory(arg1, arg2) {
  return window['go']['main']['App']['DeleteTaskHistory'](arg1, arg2);
}

export function DiscardAttachment(arg1) {
  return window['go']['main']['App']['DiscardAttachment'](arg1);
}

export function GetAgentTasks(arg1) {
  return window['go']['main']['App']['GetAgentTasks'](arg1);
}

export function GetAllUserPreferences() {
  return window['go']['main']['App']['GetAllUserPreferences']();
}

export function GetProjectMemory(arg1) {
  return window['go']['main']['App']['GetProjectMemory'](arg1);
}

export function GetProviderSettings(arg1) {
  return window['go']['main']['App']['GetProviderSettings'](arg1);
}

export function GetRemoteInfo() {
  return window['go']['main']['App']['GetRemoteInfo']();
}

export function GetSessionMeta(arg1) {
  return window['go']['main']['App']['GetSessionMeta'](arg1);
}

export function GetSessionTasks(arg1) {
  return window['go']['main']['App']['GetSessionTasks'](arg1);
}

export function GetUserPreference(arg1) {
  return window['go']['main']['App']['GetUserPreference'](arg1);
}

export function GetWorkspaceRecap(arg1) {
  return window['go']['main']['App']['GetWorkspaceRecap'](arg1);
}

export function GitCommitDiff(arg1, arg2) {
  return window['go']['main']['App']['GitCommitDiff'](arg1, arg2);
}

export function GitFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitFileDiff'](arg1, arg2, arg3);
}

export function GitOverview() {
  return window['go']['main']['App']['GitOverview']();
}

export function InterruptTurn(arg1) {
  return window['go']['main']['App']['InterruptTurn'](arg1);
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function IsProviderEnabled(arg1) {
  return window['go']['main']['App']['IsProviderEnabled'](arg1);
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function ListManagedServers() {
  return window['go']['main']['App']['ListManagedServers']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListProviders(arg1) {
  return window['go']['main']['App']['ListProviders'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListSessionsMeta(arg1) {
  return window['go']['main']['App']['ListSessionsMeta'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadHistory(arg1) {
  return window['go']['main']['App']['LoadHistory'](arg1);
}

export function MutateAgentTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MutateAgentTask'](arg1, arg2, arg3, arg4);
}

export function NewChat() {
  return window['go']['main']['App']['NewChat']();
}

export function OrchestratorAgents() {
  return window['go']['main']['App']['OrchestratorAgents']();
}

export function OrchestratorAuto() {
  return window['go']['main']['App']['OrchestratorAuto']();
}

export function OrchestratorLatest() {
  return window['go']['main']['App']['OrchestratorLatest']();
}

export function OrchestratorMessageAgent(arg1, arg2) {
  return window['go']['main']['App']['OrchestratorMessageAgent'](arg1, arg2);
}

export function OrchestratorSetAuto(arg1) {
  return window['go']['main']['App']['OrchestratorSetAuto'](arg1);
}

export function OrchestratorStopAgent(arg1) {
  return window['go']['main']['App']['OrchestratorStopAgent'](arg1);
}

export function ParseTasks(arg1) {
  return window['go']['main']['App']['ParseTasks'](arg1);
}

export function PreviewAttachment(arg1) {
  return window['go']['main']['App']['PreviewAttachment'](arg1);
}

export function RecapPrompt(arg1) {
  return window['go']['main']['App']['RecapPrompt'](arg1);
}

export function RefreshUsage() {
  return window['go']['main']['App']['RefreshUsage']();
}

export function RegenerateRemoteToken() {
  return window['go']['main']['App']['RegenerateRemoteToken']();
}

export function RemoveGitWorktree(arg1, arg2) {
  return window['go']['main']['App']['RemoveGitWorktree'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RespondToApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondToApproval'](arg1, arg2, arg3);
}

export function RespondToQuestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondToQuestion'](arg1, arg2, arg3);
}

export function ResumeHistory(arg1) {
  return window['go']['main']['App']['ResumeHistory'](arg1);
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function SaveAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2, arg3);
}

export function SaveProjectMemory(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectMemory'](arg1, arg2);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function SendTurn(arg1) {
  return window['go']['main']['App']['SendTurn'](arg1);
}

export function ServerLogs(arg1) {
  return window['go']['main']['App']['ServerLogs'](arg1);
}

export function SetProviderPermission(arg1, arg2) {
  return window['go']['main']['App']['SetProviderPermission'](arg1, arg2);
}

export function SetUserPreference(arg1, arg2) {
  return window['go']['main']['App']['SetUserPreference'](arg1, arg2);
}

export function SpawnTasks(arg1, arg2) {
  return window['go']['main']['App']['SpawnTasks'](arg1, arg2);
}

export function StartManagedServer(arg1) {
  return window['go']['main']['App']['StartManagedServer'](arg1);
}

export function StartRemoteServer(arg1) {
  return window['go']['main']['App']['StartRemoteServer'](arg1);
}

export function StartSession(arg1, arg2) {
  return window['go']['main']['App']['StartSession'](arg1, arg2);
}

export function StopManagedServer(arg1) {
  return window['go']['main']['App']['StopManagedServer'](arg1);
}

export function StopRemoteServer() {
  return window['go']['main']['App']['StopRemoteServer']();
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function SwitchTaskProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchTaskProvider'](arg1, arg2, arg3);
}

export function SwitchTaskProviderWithOptions(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SwitchTaskProviderWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function TaskHandoff(arg1) {
  return window['go']['main']['App']['TaskHandoff'](arg1);
}

export function ThreadHistory(arg1) {
  return window['go']['main']['App']['ThreadHistory'](arg1);
}

export function UpdateProviderSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateProviderSettings'](arg1, arg2);
}

export function UpdateTaskModel(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTaskModel'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UsageReport() {
  return window['go']['main']['App']['UsageReport']();
}

export function WorkspaceTasks(arg1) {
  return window['go']['main']['App']['WorkspaceTasks'](arg1);
}
