// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provider} from '../models';
import {projects} from '../models';
import {main} from '../models';
import {slashcmd} from '../models';
import {attachments} from '../models';
import {domain} from '../models';
import {session} from '../models';
import {remote} from '../models';
import {claudeimport} from '../models';
import {history} from '../models';
import {devserver} from '../models';
import {servers} from '../models';
import {skills} from '../models';
import {files} from '../models';

export function AccountStatus(arg1:string,arg2:string):Promise<provider.AccountStatus>;

export function ActiveProject():Promise<projects.Project>;

export function AddAccount(arg1:string,arg2:string,arg3:boolean):Promise<main.AccountAdded>;

export function AddProject(arg1:string):Promise<projects.Project>;

export function ChooseAttachments():Promise<Array<attachments.Attachment>>;

export function ChooseProject():Promise<projects.Project>;

export function ClaudeUpdateStatus():Promise<domain.ProviderUpdate>;

export function CompactWorkspace(arg1:string,arg2:string):Promise<string>;

export function ContextStatus(arg1:string):Promise<Record<string, any>>;

export function CoordinatorHistory():Promise<Array<domain.RuntimeEvent>>;

export function CoordinatorInterrupt():Promise<void>;

export function CoordinatorReset():Promise<void>;

export function CoordinatorSend(arg1:session.Config,arg2:string):Promise<string>;

export function CoordinatorSendFiles(arg1:session.Config,arg2:string,arg3:Array<domain.FileRef>):Promise<string>;

export function CopyAccountSettings(arg1:string,arg2:string):Promise<Array<string>>;

export function DeleteHistory(arg1:string):Promise<void>;

export function DeleteTaskHistory(arg1:string,arg2:string):Promise<void>;

export function DiscardAttachment(arg1:string):Promise<void>;

export function GetAgentTasks(arg1:string):Promise<Array<domain.PlanEntry>>;

export function GetAllUserPreferences():Promise<Record<string, string>>;

export function GetAppIcon():Promise<string>;

export function GetBackgroundSettings():Promise<main.BackgroundSettings>;

export function GetProjectMemory(arg1:string):Promise<string>;

export function GetProviderSettings(arg1:string):Promise<domain.ProviderSettings>;

export function GetRemoteInfo():Promise<remote.RemoteInfo>;

export function GetSessionMeta(arg1:string):Promise<domain.SessionRecord>;

export function GetSessionTasks(arg1:string):Promise<Array<domain.TaskRecord>>;

export function GetUserPreference(arg1:string):Promise<string>;

export function GetWorkspaceRecap(arg1:string):Promise<string>;

export function GitCommitDiff(arg1:string,arg2:string):Promise<Array<domain.DiffFile>>;

export function GitFileDiff(arg1:string,arg2:string,arg3:boolean):Promise<domain.DiffFile>;

export function GitOverview():Promise<Array<domain.WorktreeChanges>>;

export function ImportClaudeCodeSession(arg1:string):Promise<string>;

export function InterruptTurn(arg1:string):Promise<void>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function IsProviderEnabled(arg1:string):Promise<boolean>;

export function ListAccounts(arg1:string):Promise<Array<domain.Account>>;

export function ListClaudeCodeSessions():Promise<Array<claudeimport.ExternalSession>>;

export function ListHistory():Promise<Array<history.Meta>>;

export function ListManagedServers():Promise<Array<devserver.Snapshot>>;

export function ListProjects():Promise<Array<projects.Project>>;

export function ListProviders(arg1:boolean):Promise<Array<domain.ProviderSnapshot>>;

export function ListServers():Promise<Array<servers.Group>>;

export function ListSessions():Promise<Array<domain.Session>>;

export function ListSessionsMeta(arg1:number):Promise<Array<domain.SessionRecord>>;

export function ListSkills(arg1:string):Promise<Array<skills.Info>>;

export function ListSlashCommands(arg1:string,arg2:string):Promise<Array<slashcmd.Command>>;

export function ListWorkspaces():Promise<Array<domain.Workspace>>;

export function LoadHistory(arg1:string):Promise<history.Session>;

export function MoveProject(arg1:string,arg2:number):Promise<void>;

export function MutateAgentTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<domain.PlanEntry>>;

export function NewChat():Promise<void>;

export function OrchestratorAgents():Promise<Array<session.AgentView>>;

export function OrchestratorAuto():Promise<boolean>;

export function OrchestratorLatest():Promise<session.LatestPlan>;

export function OrchestratorMessageAgent(arg1:string,arg2:string):Promise<void>;

export function OrchestratorSetAuto(arg1:boolean):Promise<void>;

export function OrchestratorStopAgent(arg1:string):Promise<void>;

export function ParseTasks(arg1:string):Promise<Array<session.TaskRequest>>;

export function PreviewAttachment(arg1:string):Promise<string>;

export function ProjectFile(arg1:string,arg2:string):Promise<files.Content>;

export function ProjectIcon(arg1:string):Promise<string>;

export function ProjectTree(arg1:string,arg2:string):Promise<Array<files.Entry>>;

export function ProjectTreeStatus(arg1:string):Promise<files.TreeStatus>;

export function RecapPrompt(arg1:string):Promise<string>;

export function RefreshUsage():Promise<session.UsageReport>;

export function RegenerateRemoteToken():Promise<remote.RemoteInfo>;

export function RemoveAccount(arg1:string,arg2:string):Promise<void>;

export function RemoveGitWorktree(arg1:string,arg2:boolean):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RenameAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RespondToApproval(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RespondToQuestion(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function ResumeHistory(arg1:string):Promise<session.ResumeResult>;

export function ResumeHistoryThread(arg1:string,arg2:string):Promise<session.ResumeResult>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveAttachment(arg1:string,arg2:string,arg3:string):Promise<attachments.Attachment>;

export function SaveProjectMemory(arg1:string,arg2:string):Promise<void>;

export function SelectProject(arg1:string):Promise<projects.Project>;

export function SendTurn(arg1:domain.SendTurnInput):Promise<void>;

export function ServerLogs(arg1:string):Promise<Array<string>>;

export function SetAppIcon(arg1:string):Promise<void>;

export function SetChatArchived(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetKeepRunningOnClose(arg1:boolean):Promise<main.BackgroundSettings>;

export function SetProjectAccount(arg1:string,arg2:string,arg3:string):Promise<projects.Project>;

export function SetProviderPermission(arg1:string,arg2:boolean):Promise<void>;

export function SetStartMode(arg1:string):Promise<main.BackgroundSettings>;

export function SetUserPreference(arg1:string,arg2:string):Promise<void>;

export function SignInAccount(arg1:string,arg2:string):Promise<void>;

export function SpawnFromImported(arg1:string,arg2:string,arg3:string,arg4:string,arg5:domain.ModelOptions):Promise<session.SpawnResult>;

export function SpawnTasks(arg1:Array<session.SpawnRequest>,arg2:session.SpawnOptions):Promise<session.SpawnResult>;

export function StartManagedServer(arg1:devserver.Spec):Promise<devserver.Snapshot>;

export function StartRemoteServer(arg1:number):Promise<remote.RemoteInfo>;

export function StartSession(arg1:string,arg2:domain.SessionStartInput):Promise<domain.Session>;

export function StartSkillTest(arg1:main.SkillTestInput):Promise<session.SpawnResult>;

export function StopManagedServer(arg1:string):Promise<void>;

export function StopRemoteServer():Promise<void>;

export function StopServer(arg1:number):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function SwitchTaskAccountWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:domain.ModelOptions,arg6:string,arg7:string,arg8:string,arg9:Array<domain.FileRef>):Promise<domain.Task>;

export function SwitchTaskProvider(arg1:string,arg2:string,arg3:string):Promise<domain.Task>;

export function SwitchTaskProviderWithOptions(arg1:string,arg2:string,arg3:string,arg4:domain.ModelOptions,arg5:string,arg6:string,arg7:string,arg8:Array<domain.FileRef>):Promise<domain.Task>;

export function TaskHandoff(arg1:string):Promise<domain.TaskHandoff>;

export function ThreadHistory(arg1:string):Promise<Array<domain.RuntimeEvent>>;

export function UpdateClaudeCode():Promise<string>;

export function UpdateProviderSettings(arg1:string,arg2:domain.ProviderSettings):Promise<void>;

export function UpdateTaskModel(arg1:string,arg2:string,arg3:string,arg4:domain.ModelOptions,arg5:string,arg6:string):Promise<domain.Task>;

export function UsageReport():Promise<session.UsageReport>;

export function WorkspaceTasks(arg1:string):Promise<Array<domain.Task>>;
