// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoordinatorHistory() {
  return window['go']['main']['App']['CoordinatorHistory']();
}

export function CoordinatorInterrupt() {
  return window['go']['main']['App']['CoordinatorInterrupt']();
}

export function CoordinatorReset() {
  return window['go']['main']['App']['CoordinatorReset']();
}

export function CoordinatorSend(arg1, arg2) {
  return window['go']['main']['App']['CoordinatorSend'](arg1, arg2);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function GetProviderSettings(arg1) {
  return window['go']['main']['App']['GetProviderSettings'](arg1);
}

export function InterruptTurn(arg1) {
  return window['go']['main']['App']['InterruptTurn'](arg1);
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function ListProviders(arg1) {
  return window['go']['main']['App']['ListProviders'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadHistory(arg1) {
  return window['go']['main']['App']['LoadHistory'](arg1);
}

export function NewChat() {
  return window['go']['main']['App']['NewChat']();
}

export function ParseTasks(arg1) {
  return window['go']['main']['App']['ParseTasks'](arg1);
}

export function ResetUsage() {
  return window['go']['main']['App']['ResetUsage']();
}

export function RespondToApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondToApproval'](arg1, arg2, arg3);
}

export function ResumeHistory(arg1) {
  return window['go']['main']['App']['ResumeHistory'](arg1);
}

export function SendTurn(arg1) {
  return window['go']['main']['App']['SendTurn'](arg1);
}

export function SpawnTasks(arg1, arg2) {
  return window['go']['main']['App']['SpawnTasks'](arg1, arg2);
}

export function StartSession(arg1, arg2) {
  return window['go']['main']['App']['StartSession'](arg1, arg2);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function TaskHandoff(arg1) {
  return window['go']['main']['App']['TaskHandoff'](arg1);
}

export function ThreadHistory(arg1) {
  return window['go']['main']['App']['ThreadHistory'](arg1);
}

export function UpdateProviderSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateProviderSettings'](arg1, arg2);
}

export function UsageReport() {
  return window['go']['main']['App']['UsageReport']();
}

export function WorkspaceTasks(arg1) {
  return window['go']['main']['App']['WorkspaceTasks'](arg1);
}
