// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDetectedAgents() {
  return window['go']['main']['App']['GetDetectedAgents']();
}

export function GetLinkedProviders() {
  return window['go']['main']['App']['GetLinkedProviders']();
}

export function InitiateOAuth(arg1) {
  return window['go']['main']['App']['InitiateOAuth'](arg1);
}

export function LinkDetectedAgent(arg1, arg2) {
  return window['go']['main']['App']['LinkDetectedAgent'](arg1, arg2);
}
